### ISSUE TITLE
求助，控制台只有这个，然后没有其他输出了，是什么原因？

### ISSUE THREAD

**Issue by lisidalange** [Changbaiqi/yatori#8]
C:\Users\Administrator\Desktop\yatori.v2.0.1-Beta.1-windows-x64-jar-release>cd /d C:\Users\Administrator\Desktop\yatori.v2.0.1-Beta.1-windows-x64-jar-release\

C:\Users\Administrator\Desktop\yatori.v2.0.1-Beta.1-windows-x64-jar-release>.\jdk-17\bin\java -jar app.jar
                             ___
        ,---,              ,--.'|_                      ,--,
       /_ ./|              |  | :,'   ,---.    __  ,-.,--.'|
 ,---, |  ' :              :  : ' :  '   ,'\ ,' ,'/ /||  |,
/___/ \.  : |   ,--.--.  .;__,'  /  /   /   |'  | |' |`--'_
 .  \  \ ,' '  /       \ |  |   |  .   ; ,. :|  |   ,',' ,'|
  \  ;  `  ,' .--.  .-. |:__,'| :  '   | |: :'  :  /  '  | |
   \  \    '   \__\/: . .  '  : |__'   | .; :|  | '   |  | :
    '  \   |   ," .--.; |  |  | '.'|   :    |;  : |   '  : |__
     \  ;  ;  /  /  ,.  |  ;  :    ;\   \  / |  , ;   |  | '.'|
      :  \  \;  :   .'   \ |  ,   /  `----'   ---'    ;  :    ;
       \  ' ;|  ,     .-./  ---`-'                    |  ,   /
        `--`  `--`---'                                 ---`-'
                Yatori v2.0.0-Beta.3
         仅用于学习交流，请勿用于违法和商业用途！！！
  GitHub开源地址：https://github.com/Changbaiqi/yatori
  个人博客：https://blogs.changbaiqi.top
求助，控制台只有这个，然后没有其他输出了，是什么原因？

**Comment by Changbaiqi** [comment]
> C:\Users\Administrator\Desktop\yatori.v2.0.1-Beta.1-windows-x64-jar-release>cd /d C:\Users\Administrator\Desktop\yatori.v2.0.1-Beta.1-windows-x64-jar-release\
> 
> C:\Users\Administrator\Desktop\yatori.v2.0.1-Beta.1-windows-x64-jar-release>.\jdk-17\bin\java -jar app.jar
>                              ___
>         ,---,              ,--.'|_                      ,--,
>        /_ ./|              |  | :,'   ,---.    __  ,-.,--.'|
>  ,---, |  ' :              :  : ' :  '   ,'\ ,' ,'/ /||  |,
> /___/ \.  : |   ,--.--.  .;__,'  /  /   /   |'  | |' |`--'_
>  .  \  \ ,' '  /       \ |  |   |  .   ; ,. :|  |   ,',' ,'|
>   \  ;  `  ,' .--.  .-. |:__,'| :  '   | |: :'  :  /  '  | |
>    \  \    '   \__\/: . .  '  : |__'   | .; :|  | '   |  | :
>     '  \   |   ," .--.; |  |  | '.'|   :    |;  : |   '  : |__
>      \  ;  ;  /  /  ,.  |  ;  :    ;\   \  / |  , ;   |  | '.'|
>       :  \  \;  :   .'   \ |  ,   /  `----'   ---'    ;  :    ;
>        \  ' ;|  ,     .-./  ---`-'                    |  ,   /
>         `--`  `--`---'                                 ---`-'
>                 Yatori v2.0.0-Beta.3
>          仅用于学习交流，请勿用于违法和商业用途！！！
>   GitHub开源地址：https://github.com/Changbaiqi/yatori
>   个人博客：https://blogs.changbaiqi.top
> 求助，控制台只有这个，然后没有其他输出了，是什么原因？

注意一下是否为套壳平台，如果为套壳平台那么请修改平台类型为对应真实平台类型即可。最近一些高校使用的的仓辉平台实则为英华套壳(这点从界面布局上看得出)，如果不是以上原因建议加群私聊发我配置文件进行排查，不然我无法直接debug程序判断什么原因。

**Comment by lisidalange** [comment]
是套壳平台，改成英华平台之后就可以了，感谢

**Comment by yicuncom** [comment]
为什么一个课程它每次提交都需要好久

**Comment by Changbaiqi** [comment]
> 为什么一个课程它每次提交都需要好久

因为程序是每隔一个时间会提交一次学时，这个是根据对应平台规律来定的。如果过快提交或者过慢提交都可能会导致学时无法正常计入。

**Comment by yicuncom** [comment]
喔喔，谢谢。那请问一下它那个自动答题的功能可以答超星学习通的课程的章节测验吗



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2025年03月11日 22:55 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [yatori-dev/yatori-go-console] 求助，控制台只有这个，然后没有其他输出了，是什么原因？ (Issue #8) |

为什么一个课程它每次提交都需要好久

因为程序是每隔一个时间会提交一次学时，这个是根据对应平台规律来定的。如果过快提交或者过慢提交都可能会导致学时无法正常计入。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>

Changbaiqi left a comment (yatori-dev/yatori-go-console#8)

为什么一个课程它每次提交都需要好久

因为程序是每隔一个时间会提交一次学时，这个是根据对应平台规律来定的。如果过快提交或者过慢提交都可能会导致学时无法正常计入。

**Comment by Changbaiqi** [comment]
> 喔喔，谢谢。那请问一下它那个自动答题的功能可以答超星学习通的课程的章节测验吗
> […](#)

暂时不行，目前自动答题只支持英华、仓辉等平台。学习通的话还需要等一段时间，不过也在开发计划内。

**Comment by yicuncom** [comment]
那真是太棒啦！



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2025年03月11日 23:00 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [yatori-dev/yatori-go-console] 求助，控制台只有这个，然后没有其他输出了，是什么原因？ (Issue #8) |

喔喔，谢谢。那请问一下它那个自动答题的功能可以答超星学习通的课程的章节测验吗
…

暂时不行，目前自动答题只支持英华、仓辉等平台。学习通的话还需要等一段时间，不过也在开发计划内。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>

Changbaiqi left a comment (yatori-dev/yatori-go-console#8)

喔喔，谢谢。那请问一下它那个自动答题的功能可以答超星学习通的课程的章节测验吗
…

暂时不行，目前自动答题只支持英华、仓辉等平台。学习通的话还需要等一段时间，不过也在开发计划内。

**Comment by Changbaiqi** [comment]
> 那真是太棒啦！
> […](#)

这贞德事，泰裤辣！(ﾉ≧∀≦)ﾉ

**Comment by yicuncom** [comment]
那个可以请问一下为什么学习通明明它那个程序显示已经全部完成，在手机端查看好像总要有几个它视频任务点却是没有完成呢



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2025年03月11日 23:04 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [yatori-dev/yatori-go-console] 求助，控制台只有这个，然后没有其他输出了，是什么原因？ (Issue #8) |

那真是太棒啦！
…

这贞德事，泰裤辣！(ﾉ≧∀≦)ﾉ

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>

Changbaiqi left a comment (yatori-dev/yatori-go-console#8)

那真是太棒啦！
…

这贞德事，泰裤辣！(ﾉ≧∀≦)ﾉ

**Comment by yicuncom** [comment]
就是刚刚刷完的时候手机端是显示全完成的，可能过了一会时间，就有几个的任务点显示没完成



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2025年03月11日 23:04 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [yatori-dev/yatori-go-console] 求助，控制台只有这个，然后没有其他输出了，是什么原因？ (Issue #8) |

那真是太棒啦！
…

这贞德事，泰裤辣！(ﾉ≧∀≦)ﾉ

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>

Changbaiqi left a comment (yatori-dev/yatori-go-console#8)

那真是太棒啦！
…

这贞德事，泰裤辣！(ﾉ≧∀≦)ﾉ

**Comment by Changbaiqi** [comment]
> 就是刚刚刷完的时候手机端是显示全完成的，可能过了一会时间，就有几个的任务点显示没完成
> […](#)

在操作的过程中是否存在网页端或者其他程序也在同时刷的情况？若这种操作很可能会导致部分学习进度会打回，如果不是这个原因导致的推荐是再用程序运行一次

**Comment by yicuncom** [comment]
：）



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2025年03月14日 00:55 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [yatori-dev/yatori-go-console] 求助，控制台只有这个，然后没有其他输出了，是什么原因？ (Issue #8) |

就是刚刚刷完的时候手机端是显示全完成的，可能过了一会时间，就有几个的任务点显示没完成
…

在操作的过程中是否存在网页端或者其他程序也在同时刷的情况？若这种操作很可能会导致部分学习进度会打回，如果不是这个原因导致的推荐是再用程序运行一次

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>

Changbaiqi left a comment (yatori-dev/yatori-go-console#8)

就是刚刚刷完的时候手机端是显示全完成的，可能过了一会时间，就有几个的任务点显示没完成
…

在操作的过程中是否存在网页端或者其他程序也在同时刷的情况？若这种操作很可能会导致部分学习进度会打回，如果不是这个原因导致的推荐是再用程序运行一次
